apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: enigma-cluster-v3
  region: ap-south-1
  version: "1.32"

vpc:
  id: vpc-0ab552b80194cd476
  subnets:
    private:
      ap-south-1a:
        id: subnet-068940d08e9f541cb
      ap-south-1b:
        id: subnet-0e61d14c656db89d0

iam:
  withOIDC: true

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]

nodeGroups:
  - name: ng-workers
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 4
    volumeSize: 20
    privateNetworking: true
    ssh:
      allow: true
      publicKeyName: "enigma-ng"
    tags:
      nodegroup-role: workers
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEBSCSIDriverPolicy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy