apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-service
  namespace: enigma
  labels:
    app: job-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-service
  template:
    metadata:
      labels:
        app: job-service
    spec:
      containers:
        - name: job-service
          image: shreedev44/enigma-job:v1.0.3
          ports:
            - containerPort: 3003
          envFrom:
            - secretRef:
                name: job-secret-env
          readinessProbe:
            httpGet:
              path: /health
              port: 3003
            initialDelaySeconds: 20
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3003
            initialDelaySeconds: 25
            periodSeconds: 10