apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-pvc
  namespace: enigma
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 600Mi
  storageClassName: gp2