apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-pvc
  namespace: enigma
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Mi
  storageClassName: gp2