export const studentEndpoints = {
	SIGNUP: "/auth/student/register",
	GOOGLE_AUTH: "/auth/google-auth",
	GITHUB_AUTH: "/auth/github-auth",
	FETCH_PROFILE: "/auth/student/get-profile",
	UPDATE_PROFILE: "/auth/student/update-profile",
	GET_PROBLEMS: "/problem/get-problems",
	FIND_PROBLEM: "/problem/find-problem",
	COMPILE: "/problem/compile",
	RUN_SOLUTION: "/problem/run-solution",
	SUBMIT_SOLUTION: "/problem/attempt/submit-solution",
	GET_ATTEMPTS: "/problem/attempt/get-attempts",
	FIND_ATTEMPT: "/problem/attempt/find-attempt",
	PROBLEM_STATS: "/problem/attempt/problem-stats",
	ATTEMPT_ATTENDANCE: "/problem/attempt/attempts-per-day",
	GET_JOBS: "/job",
	GET_RECRUITER: "/auth/get-recruiter",
	APPLY_FOR_JOB: "/job/application/apply",
	MY_APPLICATIONS: "/job/application/my-applications",
	DELETE_APPLICATION: "/job/application/delete",
	LEADERBOARD_RANK: "/problem/leaderboard/rank",
	LEADERBOARD_TOP_THREE: "/problem/leaderboard/top-three",
};

export const recruiterEndpoints = {
	SIGNUP: "/auth/recruiter/register",
	GOOGLE_AUTH: "/auth/google-auth",
	FETCH_PROFILE: "/auth/recruiter/get-profile",
	UPDATE_PROFILE: "/auth/recruiter/update-profile",
	POST_JOB: "/job/create",
	MY_JOBS: "/job/recruiter-jobs",
	HIDE_JOB: "/job/hide",
	UPDATE_JOB: "/job/update",
	APPLICATIONS: "/job/application/job-applications",
	SHORTLIST_APPLICATIONS: "/job/application/shortlist-applications",
	GET_SHORTLIST: "/job/application/shortlist",
	DOWNLOAD_RESUME: "/job/application/download-resume",
	APPLICATOIN_DETAILS: "/job/application",
	SHORTLIST_SINGLE_APPLICATION: "/job/application/shortlist-application",
	REMOVE_FROM_SHORTLIST: "/job/application/remove-from-shortlist",
	SCHEDULE_INTERVIEW: "/job/interview/schedule",
};

export const adminEndpoints = {
	FETCH_STUDENTS: "/auth/admin/get-students",
	FETCH_RECRUITERS: "/auth/admin/get-recruiters",
	BLOCK_ACTION: "/auth/admin/block-or-unblock",
	ADD_PROBLEM: "/problem/add-problem",
	FIND_PROBLEM: "/problem/find-problem",
	UPDATE_PROBLEM: "/problem/update-problem",
	UNLIST_PROBLEM: "/problem/unlist-problem",
	LIST_PROBLEM: "/problem/list-problem",
	GET_JOBS: "/job",
	USER_STATS: "/auth/admin/user-stats",
	JOB_STATS: "/job/application/job-stats",
	PROBLEM_STATS: "/problem/attempt/attempt-stats",
};

export const commonEndpoints = {
	VERIFY_OTP: "/auth/verify-otp",
	RESEND_OTP: "/auth/resend-otp",
	SIGNIN: "/auth/signin",
	FORGOT_PASSWORD: "/auth/change-password",
	RESET_PASSWORD: "/auth/reset-password",
	REFRESH_TOKEN: `${import.meta.env.VITE_BASE_URL}/auth/refresh-token`,
	LOGOUT: "/auth/logout",
	GET_JOBS: "/job",
	HIDE_JOB: "/job/hide",
};
