apiVersion: v1
kind: Service
metadata:
  name: authentication-service
  namespace: enigma
  labels:
    app: authentication-service
spec:
  selector:
    app: authentication-service
  ports:
    - port: 3001
      targetPort: 3001
  type: ClusterIP