apiVersion: v1
kind: Service
metadata:
  name: job-service
  namespace: enigma
  labels:
    app: job-service
spec:
  selector:
    app: job-service
  ports:
    - port: 3003
      targetPort: 3003
  type: ClusterIP