apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: enigma
  labels:
    app: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: zookeeper
          image: bitnami/zookeeper:3.9
          ports:
            - containerPort: 2181
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
          volumeMounts:
            - name: zookeeper-storage
              mountPath: /bitnami/zookeeper
          livenessProbe:
            exec:
              command: ["zkServer.sh", "status"]
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["zkServer.sh", "status"]
            initialDelaySeconds: 15
            periodSeconds: 10
      volumes:
        - name: zookeeper-storage
          persistentVolumeClaim:
            claimName: zookeeper-pvc