apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: enigma
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: shreedev44/enigma-notification:v1.0.1
        ports:
          - containerPort: 3004
        envFrom:
          - secretRef:
              name: notification-secret-env
        readinessProbe:
          httpGet:
            path: /health
            port: 3004
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3004
          initialDelaySeconds: 30
          periodSeconds: 20