services:
  authentication-service:
    build: 
      context: ./authentication/
      dockerfile: Dockerfile
    container_name: enigma-authentication
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MONGO_URI=mongodb+srv://shreedevchambayil:u2NefgQ4fdjqYztZ@cluster0.kicd2.mongodb.net/Authentication?retryWrites=true&w=majority&appName=Cluster0
      - JWT_ACCESS_SECRET=gX9$9d7L!E4R&hN^zM3k8T@Qp1y2Wj*cA0E5X!mNz7$F3v^K
      - JWT_REFRESH_SECRET=gF9@N3x?8Tq$Z8j*L!v7B&mX1YpRk^2W6Vh5%C4+HdU!JzKq
      - REDIS_URL=redis://redis:6379
      - USER_EMAIL=nm6484670@gmail.com
      - USER_PASS=fvpv axcs gzzo kcvp
      - GITHUB_CLIENT_ID=Ov23li37fVuaE3lWjS6N
      - GITHUB_SECRET=42412ff5c4d3de67e90e96f35b488a9754c7267c
      - FRONTEND_ORIGIN=http://localhost:5173
      - CLOUDINARY_API_KEY=623399777378525
      - CLOUDINARY_API_SECRET=2uvWJ2VyzGG8wDgyKnHwuGobDOM
    volumes:
      - ./authentication:/app
      - /app/node_modules 
    command: sh -c "npm install && npm run dev"
    depends_on:
      - redis
    networks:
      - enigma-network

  problem-service:
    build: 
      context: ./problem/
      dockerfile: Dockerfile
    container_name: enigma-problem
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - MONGO_URI=mongodb+srv://shreedevchambayil:u2NefgQ4fdjqYztZ@cluster0.kicd2.mongodb.net/Problem?retryWrites=true&w=majority&appName=Cluster0
    volumes:
      - ./problem:/app 
      - /app/node_modules 
    command: sh -c "npm install && npm run dev"
    networks:
      - enigma-network

  api-gateway:
    build: 
      context: ./api-gateway/
      dockerfile: Dockerfile
    container_name: enigma-api-gateway
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - AUTH=http://localhost:3001
      - PROBLEM=http://localhost:3002
      - JWT_ACCESS_SECRET=gX9$9d7L!E4R&hN^zM3k8T@Qp1y2Wj*cA0E5X!mNz7$F3v^K
    volumes:
      - ./api-gateway:/app
      - /app/node_modules 
    command: sh -c "npm install && npm run dev"
    networks:
      - enigma-network

  redis:
    container_name: enigma-redis
    image: "redis:7.4"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - enigma-network

volumes:
  redis_data:

networks:
  enigma-network:
    driver: bridge