services:
  authentication-service:
    image: shreedev44/enigma-authentication:latest
    pull_policy: always
    container_name: authentication-container
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MONGO_URI=mongodb+srv://shreedevchambayil:u2NefgQ4fdjqYztZ@cluster0.kicd2.mongodb.net/Authentication?retryWrites=true&w=majority&appName=Cluster0
      - JWT_ACCESS_SECRET=gX9$9d7L!E4R&hN^zM3k8T@Qp1y2Wj*cA0E5X!mNz7$F3v^K
      - JWT_REFRESH_SECRET=gF9@N3x?8Tq$Z8j*L!v7B&mX1YpRk^2W6Vh5%C4+HdU!JzKq
      - REDIS_URI=redis://redis:6379
      - USER_EMAIL=nm6484670@gmail.com
      - USER_PASS=fvpv axcs gzzo kcvp
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - 6380:6380
    volumes:
      - redis_data:/data
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  redis_data: