export const Messages = {
    SERVER_ERROR: 'Internel server error',
    PROBLEM_TITLE_EXIST: 'Problem already exist with the given title',
    INVALID_REQUEST: 'Invalid request',
    DATATYPE_NOT_MATCHING: 'The datatypes of the parameter and test case input does not match',
    INVALID_EVAL: 'Please provide a valid evaluating function',
    TITLE_REQUIRED: 'Problem title is required',
    DIFFICULTY_REQUIRED: 'Problem difficulty is required',
    DESCRIPTION_REQUIRED: 'Problem description is required',
    FUNCTION_NAME_REQUIRED: 'Problem function name is required',
    NOT_ENOUGHT_PARAMS: 'Please provide atleast 1 parameter',
    NOT_ENOUGHT_TEST_CASES: 'Please provide atleast 5 test cases',
    FUNCTION_RETURN_REQUIRED: 'Please provide function return type',
    FUNCTION_RETURN_ELEMENT_REQUIRED: 'Please provide the function return element type',
    FUNCTION_RETURN_NESTED_REQUIRED: 'Please provide the function nested return element type',
    EVAL_FUNCTION_REQUIRED: 'Please provide evaluating function',
    PROBLEM_ADDED: 'Problem added successfully',
    INVALID_SORT_OPTION: 'Invalid sort option',
    INVALID_SORT_VALUE: 'Invalid sort value',
    INVALID_FILTER_OPTION: 'Invalid filter option',
    INVALID_FILTER_VALUE: 'Invalid filter value',
    INVALID_PAGE: 'Invalid page selected',
    PROBLEM_NOT_FOUND: 'Problem not found',
    INVALID_PROBLEM_NO: 'Please provide a valid problem number',
    UNSUPPORTED_LANGUAGE: 'Code language not supported',
    SOLUTION_REQUIRED: 'Please provide a solution',
    FAILED_TESTCASE: 'Failed test case',
    ATTEMPT_NOT_FOUND: 'Attempt not found',
    STATS_NOT_RETRIEVED: 'Problem stats cannot be retrieved at the moment',
    ATTENDANCE_NOT_RETRIEVED: 'Attempt attendance cannot be retrieved',
    RANKS_UPDATED: 'Ranks updated successfully',
    USER_NOT_FOUND: 'User not found',
}
