apiVersion: apps/v1
kind: Deployment
metadata:
  name: dind
  namespace: enigma
  labels:
    app: dind
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dind
  template:
    metadata:
      labels:
        app: dind
    spec:
      containers:
        - name: dind
          image: docker:24-dind
          securityContext:
            privileged: true
          env:
            - name: DOCKER_TLS_CERTDIR
              value: ""
          command: ["dockerd", "--host=tcp://0.0.0.0:2375", "--tls=false"]
          ports:
            - containerPort: 2375
          volumeMounts:
            - name: shared-temp
              mountPath: /app/temp
      volumes:
        - name: shared-temp
          persistentVolumeClaim:
            claimName: shared-temp-pvc