apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: enigma
  labels:
    app: notification-service
spec:
  selector:
    app: notification-service
  ports:
    - port: 3004
      targetPort: 3004
  type: ClusterIP