export const Messages = {
    SERVER_ERROR: 'Internal server error',
    UNAUTHORIZED: 'Unauthorized access',
    INCOMPLETE_FORM: 'Complete the form',
    NO_ACCESS: 'Unauthorized',
    NO_PROFILE: 'Profile missing',
    INVALID_REQUEST: 'Invalid request',
    JOB_NOT_FOUND: 'Job missing',
    JOB_DELETED: 'Job is hidden now',
    JOB_UPDATED: 'Job updated',
    INVALID_COMPANY_NAME: 'Invalid company name',
    INVALID_PROFILE_PICTURE: 'Invalid profile picture url',
    FAILED_TO_UPLOAD: 'Failed to upload file',

    INVALID_PAGE: 'Invalid page number',
    INVALID_SORT_OPTION: 'Invalid sort parameter',
    INVALID_SORT_ORDER: 'Invalid sort order',

    INVALID_ROLE: 'Role must be 3-50 chars, letters & spaces only',
    INVALID_WORK_TIME: 'Work time must be "Full-Time" or "Part-Time"',
    INVALID_WORK_MODE: 'Work mode must be "On-Site", "Remote", or "Hybrid"',
    INVALID_JOB_LOCATION: 'Location must be 3-100 chars, letters, commas & spaces only',
    INVALID_MINIMUM_EXPERIENCE: 'Experience must be 1-2 digits',
    INVALID_SALARY: 'Salary must be 1-2 digits',
    INVALID_REQUIREMENTS: 'At least 3 requirements needed',
    INVALID_RESPONSIBILITIES: 'At least 3 responsibilities needed',
    INVALID_LAST_DATE: 'Date must be YYYY-MM-DD',
    INVALID_ID: 'Invalid id',

    APPLICATION_NOT_FOUND: 'Application not found',
    INVALID_FILE_TYPE: 'Only pdf files allowed',
    APPLICATION_DELETED: 'Application deleted',
    APPLICATION_EXISTS: 'You have already applied for this job',
    FAILED_TO_PARSE: (field: string) => `Failed to parse ${field}, Use an ATS friendly resume`,
    SHORTLISTED: (count: number) => `${count} Application${count > 1 ? 's' : ''} was shortlisted`,
    APPLICATION_SUCCESS: 'Applied for job',
    APPLICATOIN_SHORTLISTED: 'Application shortlisted',
    REMOVED_FROM_SHORTLIST: 'Applicatoin removed from shortlist',

    INVALID_PLAN_NAME: 'Invalid plan name',
    INVALID_FEATURES: 'Atleast 1 feature is required',
    INVALID_PRICE: 'Invalid price',
    INVALID_DURATION: 'Invalid plan duration',
    PLAN_ADDED: 'Subscription plan added',
    PLAN_LISTED: 'Plan is now listed for the user',
    PLAN_UNLISTED: 'Plan is now unlisted from the user',
    PLAN_NOT_FOUND: 'Plan is not found',

    PAYMENT_FAILED: 'Payment verification failed',
    SESSION_NOT_FOUND: 'Payment session not found',
    SIGNATURE_NOT_FOUND: 'Signature not found',
    NO_SUBSCRIPTION: 'No current subscriptions',
    LIMIT_REACHED: 'Your max interview limit reached',
}
