apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: enigma-api-cert
  namespace: enigma
spec:
  secretName: enigma-api-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: enigma.shreedev.space
  dnsNames:
    - enigma.shreedev.space