apiVersion: v1
kind: Pod
metadata:
  name: kafka-debug
  namespace: enigma
spec:
  containers:
    - name: debug
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - name: kafka-storage
          mountPath: /opt/bitnami/kafka
  volumes:
    - name: kafka-storage
      persistentVolumeClaim:
        claimName: kafka-pvc
  restartPolicy: Never
