apiVersion: v1
kind: Pod
metadata:
  name: irsa-debug
  namespace: kube-system
spec:
  serviceAccountName: efs-csi-controller-sa
  containers:
  - name: awscli
    image: amazonlinux
    command: [ "sh", "-c", "sleep 3600" ]