apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: enigma
data:
  loki-config.yaml: |
    auth_enabled: false

    server:
      http_listen_port: 3100

    limits_config:
      allow_structured_metadata: false

    ingester:
      lifecycler:
        address: 127.0.0.1
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
      chunk_idle_period: 5m
      chunk_retain_period: 30m
      wal:
        enabled: true
        dir: /loki/wal

    schema_config:
      configs:
        - from: 2025-05-28
          store: boltdb
          object_store: filesystem
          schema: v11
          index:
            prefix: loki_index_
            period: 24h

    storage_config:
      boltdb:
        directory: /tmp/loki/index
      filesystem:
        directory: /tmp/loki/chunks

    compactor:
      working_directory: /tmp/loki/boltdb-shipper-working-dir
      compaction_interval: 1h
      retention_enabled: false
