export const Messages = {
    SERVER_ERROR: 'Internel server error',
    USER_EXIST: 'User already exist',
    LOGOUT: 'Logout successfull',
    OTP_ERROR: 'Error while sending OTP, Try again later',
    OTP_RESENT: 'OTP has been resent successfully',
    INVALID_ID: 'Invalid ID',
    INVALID_NAME: 'Please enter a valid name (A - Z)',
    INVALID_EMAIL: 'Please enter a valid email',
    PASSWORD_LENGTH: 'Your password must be at least 8 characters long',
    PASSWORD_LETTER: 'Your password must contain at least one letter',
    PASSWORD_DIGIT: 'Your password must contain at least one number',
    PASSWORD_SPECIALCHAR: 'Your password must contain at least one special character',
    INCOMPLETE_FORM: 'Please complete the form',
    OTP_EXPIRED: 'Your OTP has been expired, try again',
    INCORRECT_OTP: 'The OTP you provided is incorrect',
    OTP_VERIFIED: 'OTP verification successful',
    USER_NOT_FOUND: 'User not found, try to signup',
    PASSWORD_INCORRECT: 'Incorrect password, try again',
    USER_BLOCKED: 'Your are blocked from Enigma, Please contact support',
    NO_ACCESS: 'Unauthorized Access',
    NO_EMAIL: 'Your github email is not public',
    USE_SOCIAL: 'Your account is created using social account',
    LINK_SENT: 'Password reset link has been sent to your mail',
    LINK_EXPIRED: 'Your link has been expired',
    PASSWORD_CHANGED: 'Password has been changed successfully',
    INVALID_TOKEN: 'Invalid refresh token',
    NO_TOKEN: 'Token not provided',
    NO_PROFILE: 'Profile not found',
    INVALID_REQUEST: 'Invalid request',
    INVALID_GITHUB: 'Please provide a valid github profile link',
    INVALID_LINKEDIN: 'Please provide a valid linked profile link',
    INVALID_FILE_TYPE: 'Only jpeg, jpg, webp and png files allowed',
    FILE_SIZE_EXCEEDED: 'Image size cannot exceed 5MB',
    FAILED_TO_UPLOAD: 'Failed to upload image',
    INVALID_BIO: 'Bio should contains 100 - 600 characters',
    INVALID_FACEBOOK: 'Please provide a valid facebook profile link',
    INVALID_TWITTER: 'Please provide a valid twitter profile link',
    INVALID_BASED_AT: 'Please provide a valid location',
    INVALID_SORT_OPTION: 'Invalid sort option',
    INVALID_SORT_VALUE: 'Invalid sort value',
    INVALID_PAGE: 'Invalid page selected',
    BLOCKED: 'User blocked successfully',
    UNBLOCKED: 'User unblocked successfully',
    SKILLS_UPDATED: 'Skills updated',
}
