apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-temp-pvc
  namespace: enigma
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard