name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
      GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
      GKE_ZONE: ${{ secrets.GKE_ZONE }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Docker Login
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Docker Images for All Services
      run: |
        MODULES=("api-gateway" "authentication" "problem" "job" "notification")

        for MODULE in "${MODULES[@]}"; do
          MODULE_PATH="server/$MODULE"
          if [ -f "$MODULE_PATH/VERSION" ]; then
            VERSION=$(cat "$MODULE_PATH/VERSION")
            IMAGE="${DOCKER_USERNAME}/enigma-$MODULE:v$VERSION"

            echo "🚀 Building $IMAGE"
            docker build -f "$MODULE_PATH/Dockerfile.production" -t "$IMAGE" "$MODULE_PATH"
            docker push "$IMAGE"
          else
            echo "⚠️ Skipping $MODULE — VERSION file not found at $MODULE_PATH"
          fi
        done

    - name: Install GCloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GKE_PROJECT }}

    - name: Authenticate with GCP (via base64 key)
      run: |
        echo "${{ secrets.GKE_SA_KEY_BASE64 }}" | base64 -d > key.json
        gcloud auth activate-service-account --key-file=key.json
        gcloud config set project "${GKE_PROJECT}"
        gcloud auth list

    - name: Get GKE Credentials
      run: |
        export USE_GKE_GCLOUD_AUTH_PLUGIN=False
        gcloud container clusters get-credentials "$GKE_CLUSTER" --region "$GKE_ZONE" --project "$GKE_PROJECT"

    - name: Apply Kubernetes Deployments
      run: |
        export USE_GKE_GCLOUD_AUTH_PLUGIN=False
        for MODULE in api-gateway authentication problem job notification; do
          YAML="server/k8s/production/gcp/services/$MODULE/deployment.yaml"
          if [ -f "$YAML" ]; then
            echo "📦 Applying $YAML"
            kubectl apply -f "$YAML"
          else
            echo "❌ No deployment.yaml for $MODULE at $YAML"
          fi
        done
